// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqohlkobrsnlqpybvoly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxb2hsa29icnNubHFweWJ2b2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDAxMDgsImV4cCI6MjA2NTcxNjEwOH0.dDSEpT91-6V2VbMJIoc9aqeMslgFtTZocVXtbOZTpnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);